name: CI (Windows)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Build
        env:
          ENCRYPTION_CODE: ${{ secrets.ENCRYPTION_CODE }}
        run: |
          dotnet build BatteryMonitor/BatteryMonitor.csproj -c Release

      - name: Run (example)
        env:
          ENCRYPTION_CODE: ${{ secrets.ENCRYPTION_CODE }}
        run: |
          echo "ENCRYPTION_CODE set: ${ENV:ENCRYPTION_CODE:-<not-set>}"
